baseURL = 'https://vittorioponti.com'
languageCode = 'en-us'
title = 'Vittorio Ponti'
theme = 'drishtikon'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    # Uncomment if you have a logo image
    # logo = "/path-to-your-logo"

    # Profile section for homepage
    profilePhoto = "/assets/foto_convertita.png"
    profileDescription = """"""
    profileUpdates = """Mi chiamo Vittorio Ponti, sono psicologo e specializzando in psicoterapia sistemico-dialogica.
    Mi occupo di disturbi d'ansia, dell'umore e di personalit√†"""
    email = "mailto:vittorio.ponti34@gmail.com"
    linkedin = "https://www.linkedin.com/"
    math = true

    # Uncomment if you want to customize the colors
    # backgroundColor = "#f9dc90"
    # linksColor = "#805690"
    # textColor = "#333"
    fontFamily = "Lora"
    # tableHeaderColor = "#d46f93"
    # tableContentColor = "#f89e9d"
    # tableRowHoverColor = "#ffbbba"
    # writingCardBackground = "#fdf1cd"    

[permalinks]
    posts = "/blog/:slug/"

[menu]
    [[menu.main]]
        name = "cv"
        url = "/cv/"
        weight = 20
    [[menu.main]]
        name = "contatti"
        url = "/contatti/"
        weight = 30
