baseURL = 'https://vittorioponti.com'
languageCode = 'en-us'
title = 'Vittorio Ponti'
theme = 'drishtikon'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    # Logo image
logo = "/assets/logo.svg"


    # Profile section for homepage
    profilePhoto = "/assets/foto_convertita.png"
   profileDescription = """
Sono Vittorio Ponti, psicologo iscritto all’Ordine degli Psicologi della Lombardia. Dopo la laurea in Psicologia presso l’Università di Trento, ho maturato esperienza sia in ambito clinico sia organizzativo. Lavoro con individui, coppie e gruppi. Mi occupo di temi come disturbi d'ansia, problematiche relazionali, dipendenza affettiva e difficoltà lavorative.

[<span style='font-size:20px; display:inline-block; margin-top:20px; font-weight:bold;'>Prenota un appuntamento</span>](https://www.doctolib.it/psicologo/bergamo/vittorio-ponti)
"""


    profileUpdates = """"""
    bookingUrl = "https://www.doctolib.it/psicologo/bergamo/vittorio-ponti"
    email = "mailto:vittorio.ponti34@gmail.com"
    linkedin = "https://www.linkedin.com/"
    math = true

    # Uncomment if you want to customize the colors
    backgroundColor = "#DAD6D6"
    # linksColor = "#805690"
    # textColor = "#333"
    fontFamily = "Lora"
    # tableHeaderColor = "#d46f93"
    # tableContentColor = "#f89e9d"
    # tableRowHoverColor = "#ffbbba"
    # writingCardBackground = "#fdf1cd"    

[permalinks]
    posts = "/blog/:slug/"

[menu]
    [[menu.main]]
        name = "cv"
        url = "/cv/"
        weight = 20
    [[menu.main]]
        name = "contatti"
        url = "/contatti/"
        weight = 30
