baseURL = 'https://vittorioponti.com'
languageCode = 'en-us'
title = 'Vittorio Ponti'
theme = 'drishtikon'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
    # Uncomment if you have a logo image
    # logo = "/path-to-your-logo"

    # Profile section for homepage
    profilePhoto = "/assets/foto_convertita.png"
    profileDescription = """"""
    profileUpdates = """Mi chiamo Vittorio Ponti e sono uno psicologo iscritto all’Ordine degli Psicologi della Lombardia. Dopo la laurea in Psicologia presso l’Università di Trento, ho maturato esperienza sia in ambito clinico sia organizzativo, lavorando a stretto contatto con persone, coppie e gruppi.
    
    
Mi occupo di supporto psicologico su tematiche quali la gestione dello stress, i disturbi d’ansia e le difficoltà relazionali, accompagnando le persone nella comprensione delle dinamiche che attraversano nei diversi contesti della loro vita, personali e lavorativi. Lavoro attraverso percorsi individuali, interventi di coppia e incontri di gruppo.


Il mio approccio si fonda sul dialogo come strumento di costruzione di significato. Considero la persona all’interno dei contesti e delle relazioni che abita, partendo dal presupposto che ogni paziente è il principale conoscitore della propria esperienza. Insieme, attraverso l’esplorazione delle emozioni e delle posizioni relazionali, costruiamo nuove letture e possibilità di cambiamento."""
    email = "mailto:vittorio.ponti34@gmail.com"
    linkedin = "https://www.linkedin.com/"
    math = true

    # Uncomment if you want to customize the colors
    # backgroundColor = "#f9dc90"
    # linksColor = "#805690"
    # textColor = "#333"
    fontFamily = "Lora"
    # tableHeaderColor = "#d46f93"
    # tableContentColor = "#f89e9d"
    # tableRowHoverColor = "#ffbbba"
    # writingCardBackground = "#fdf1cd"    

[permalinks]
    posts = "/blog/:slug/"

[menu]
    [[menu.main]]
        name = "cv"
        url = "/cv/"
        weight = 20
    [[menu.main]]
        name = "contatti"
        url = "/contatti/"
        weight = 30
